name: ViewSlimeChunk
version: '${project.version}'
main: top.e404.viewslimechunk.Main
api-version: 1.13
authors: [ 404E ]
commands:
  slime:
    description: "插件主命令"
  slimereload:
    description: "重载插件"
permissions:
  viewslimechunk.use:
    default: op
  viewslimechunk.admin:
    default: op
